-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(os.SALES_AMOUNT * p.PRICE) as SALES
FROM PRODUCT p
inner join OFFLINE_SALE os on p.PRODUCT_ID=os.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE ASC;