-- 코드를 입력하세요
SELECT mp.MEMBER_ID, mp.MEMBER_NAME, mp.GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE mp 
WHERE GENDER="W" AND MONTH(mp.DATE_OF_BIRTH) = 3 AND TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC