-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
inner join AUTHOR on AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
WHERE CATEGORY='경제'
ORDER BY PUBLISHED_DATE ASC;